---
# file: nginx/tasks/main.yml

- include: clean.yml
  when: nginx_reinstall == true

- include: package.yml
  when: nginx_install_method == "package"

- include: source/build_tools.yml
  when: nginx_install_method == "source"

- include: source.yml
  when: nginx_install_method == "source"

- include: shared/main.yml
  when: nginx_install_method == "source" or nginx_install_method == "package"
