---
# file: nginx/tasks/main.yml

- shell: apt-get remove --purge apache2
  when: nginx_uninstall_apache == true

- apt: name=apache2* state=absent purge=yes
  when: nginx_uninstall_apache == true

- include: clean.yml
  when: nginx_reinstall == true

- include: package.yml
  when: nginx_install_method == "package"

- include: source/build_tools.yml
  when: nginx_install_method == "source"

- include: source.yml
  when: nginx_install_method == "source"

- include: shared/main.yml
  when: nginx_install_method == "source" or nginx_install_method == "package"

- service: name=nginx state=started enabled=yes
