# file: nginx/tasks/package.yml

#- name: Stop apache2 if it exists.
#  service: name=apache2 state=stopped must_exist=false

- name: Install Nginx.
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - nginx-common
    - nginx-full
  notify:
    - restart nginx

- include: shared/directories.yml
