# file: nginx/handlers/main.yml

- name: restart nginx
  service: name=nginx state=restarted
  become: true
  when: not nginx_first_start.changed

- name: reload nginx
  service: name=nginx state=reloaded
  become: true
